services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: buzzDB
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    expose:
      - 3306

volumes:
  data:


secrets:
  db-password:
    file: src/db/password.txt
